// cargarDatos.js
const sequelize = require('./model/db');
const {
  Ala,
  Habitacion,
  Cama,
  Nacionalidad,
  Paciente,
  SeguroMedico,
  Turno
} = require('./model');

(async () => {
  try {
    await sequelize.sync({ force: true });
    console.log('Base de datos sincronizada');

    await Ala.bulkCreate([
      { nombre: 'Clínica', descripcion: 'Área de medicina general y diagnóstica' },
      { nombre: 'Cirugía', descripcion: 'Área destinada a intervenciones quirúrgicas' },
      { nombre: 'Pediatría', descripcion: 'Área especializada en atención infantil' },
      { nombre: 'Emergencias', descripcion: 'Área de atención urgente y crítica' }
    ]);

    await Nacionalidad.bulkCreate([
      { nombre: "Afgana" },
      { nombre: "Alemana" },
      { nombre: "Argentina" },
      { nombre: "Australiana" },
      { nombre: "Belga" },
      { nombre: "Boliviana" },
      { nombre: "Brasileña" },
      { nombre: "Canadiense" },
      { nombre: "Chilena" },
      { nombre: "China" },
      { nombre: "Colombiana" },
      { nombre: "Coreana" },
      { nombre: "Cubana" },
      { nombre: "Danesa" },
      { nombre: "Ecuatoriana" },
      { nombre: "Egipcia" },
      { nombre: "Salvadoreña" },
      { nombre: "Española" },
      { nombre: "Estadounidense" },
      { nombre: "Filipina" },
      { nombre: "Finlandesa" },
      { nombre: "Francesa" },
      { nombre: "Griega" },
      { nombre: "Guatemalteca" },
      { nombre: "Hondureña" },
      { nombre: "India" },
      { nombre: "Indonesa" },
      { nombre: "Irlandesa" },
      { nombre: "Israelí" },
      { nombre: "Italiana" },
      { nombre: "Japonesa" },
      { nombre: "Libanesa" },
      { nombre: "Malaya" },
      { nombre: "Marroquí" },
      { nombre: "Mexicana" },
      { nombre: "Nicaragüense" },
      { nombre: "Noruega" },
      { nombre: "Neozelandesa" },
      { nombre: "Panameña" },
      { nombre: "Paraguaya" },
      { nombre: "Peruana" },
      { nombre: "Polaca" },
      { nombre: "Portuguesa" },
      { nombre: "Puertorriqueña" },
      { nombre: "Británica" },
      { nombre: "Rumana" },
      { nombre: "Rusa" },
      { nombre: "Sueca" },
      { nombre: "Suiza" },
      { nombre: "Uruguaya" },
      { nombre: "Venezolana" },
      { nombre: "Albanesa" },
      { nombre: "Algerina" },
      { nombre: "Andorrana" },
      { nombre: "Angoleña" },
      { nombre: "Antiguana y barbudense" },
      { nombre: "Armenia" },
      { nombre: "Austriaca" },
      { nombre: "Azerbaiyana" },
      { nombre: "Bahameña" },
      { nombre: "Bareiní" },
      { nombre: "Bangladesí" },
      { nombre: "Barbadense" },
      { nombre: "Bielorrusa" },
      { nombre: "Beliceña" },
      { nombre: "Beninesa" },
      { nombre: "Butanesa" },
      { nombre: "Botsuana" },
      { nombre: "Bosnia" },
      { nombre: "Botswanesa" },
      { nombre: "Bruneana" },
      { nombre: "Búlgara" },
      { nombre: "Burkinesa" },
      { nombre: "Burundesa" },
      { nombre: "Cabo Verdiana" },
      { nombre: "Camboyana" },
      { nombre: "Camerunesa" },
      { nombre: "Centroafricana" },
      { nombre: "Chadiana" },
      { nombre: "Checa" },
      { nombre: "Chipriota" },
      { nombre: "Congoleña" },
      { nombre: "Costarricense" },
      { nombre: "Croata" },
      { nombre: "Djibutiana" },
      { nombre: "Dominicana" },
      { nombre: "Dominicana (República)" },
      { nombre: "Timorense" },
      { nombre: "Egipcia" },
      { nombre: "Emiratí" },
      { nombre: "Eritrea" },
      { nombre: "Eslovaca" },
      { nombre: "Eslovena" },
      { nombre: "Estonia" },
      { nombre: "Etíope" },
      { nombre: "Fiyiana" },
      { nombre: "Gabonesa" },
      { nombre: "Gambiana" },
      { nombre: "Georgiana" },
      { nombre: "Ghanesa" },
      { nombre: "Granadina" },
      { nombre: "Guineana" },
      { nombre: "Guineana-Bisau" },
      { nombre: "Guyanesa" },
      { nombre: "Haitiana" },
      { nombre: "Húngara" },
      { nombre: "Islandesa" },
      { nombre: "Iraní" },
      { nombre: "Iraquí" },
      { nombre: "Jamaicana" },
      { nombre: "Jordana" },
      { nombre: "Kazaja" },
      { nombre: "Keniata" },
      { nombre: "Kirguís" },
      { nombre: "Kiribatiana" },
      { nombre: "Kuwaití" },
      { nombre: "Laosiana" },
      { nombre: "Lesotense" },
      { nombre: "Letona" },
      { nombre: "Liberiana" },
      { nombre: "Libia" },
      { nombre: "Liechtensteiniana" },
      { nombre: "Lituana" },
      { nombre: "Luxemburguesa" },
      { nombre: "Macedonia" },
      { nombre: "Malagache" },
      { nombre: "Malauí" },
      { nombre: "Maldiva" },
      { nombre: "Maliense" },
      { nombre: "Maltesa" },
      { nombre: "Marfileña" },
      { nombre: "Mauriciana" },
      { nombre: "Mauritana" },
      { nombre: "Micronesia" },
      { nombre: "Moldava" },
      { nombre: "Monegasca" },
      { nombre: "Mongola" },
      { nombre: "Montenegrina" },
      { nombre: "Mozambiqueña" },
      { nombre: "Namibia" },
      { nombre: "Nauruana" },
      { nombre: "Nepalí" },
      { nombre: "Nigeriana" },
      { nombre: "Nigerina" },
      { nombre: "Norcoreana" },
      { nombre: "Omaní" },
      { nombre: "Pakistaní" },
      { nombre: "Palaosiana" },
      { nombre: "Palestina" },
      { nombre: "Papú" },
      { nombre: "Qatarí" },
      { nombre: "Centroafricana" },
      { nombre: "Congoleña (Rep. Dem.)" },
      { nombre: "Ruandesa" },
      { nombre: "Samoana" },
      { nombre: "Sanmarinense" },
      { nombre: "Santomense" },
      { nombre: "Senegalesa" },
      { nombre: "Serbia" },
      { nombre: "Seychellense" },
      { nombre: "Sierraleonesa" },
      { nombre: "Singapurense" },
      { nombre: "Siria" },
      { nombre: "Somalí" },
      { nombre: "Sri Lanka" },
      { nombre: "Suazi" },
      { nombre: "Sudafricana" },
      { nombre: "Sudanesa" },
      { nombre: "Surinamesa" },
      { nombre: "Tailandesa" },
      { nombre: "Tanzana" },
      { nombre: "Tayika" },
      { nombre: "Togolesa" },
      { nombre: "Tonga" },
      { nombre: "Trinitense" },
      { nombre: "Tunecina" },
      { nombre: "Turca" },
      { nombre: "Turkmena" },
      { nombre: "Tuvaluana" },
      { nombre: "Ucraniana" },
      { nombre: "Ugandesa" },
      { nombre: "Uzbeca" },
      { nombre: "Vanuatuense" },
      { nombre: "Vaticana" },
      { nombre: "Vietnamita" },
      { nombre: "Yemení" },
      { nombre: "Zambiana" },
      { nombre: "Zimbabuense" }
    ]);

    await Habitacion.bulkCreate([
      {numero: 101, capacidad: 2, idAla: 1 },
      {numero: 102, capacidad: 2, idAla: 1 },
      {numero: 103, capacidad: 2, idAla: 1 },
      {numero: 104, capacidad: 2, idAla: 1 },
      {numero: 105, capacidad: 2, idAla: 1 },
      {numero: 106, capacidad: 2, idAla: 1 },
      {numero: 107, capacidad: 2, idAla: 1 },
      {numero: 108, capacidad: 2, idAla: 1 },
      {numero: 109, capacidad: 2, idAla: 1 },
      {numero: 110, capacidad: 2, idAla: 1 },
      {numero: 111, capacidad: 2, idAla: 1 },
      {numero: 112, capacidad: 2, idAla: 1 },
      {numero: 113, capacidad: 2, idAla: 1 },
      {numero: 114, capacidad: 2, idAla: 1 },
      {numero: 115, capacidad: 2, idAla: 1 },
      {numero: 116, capacidad: 2, idAla: 1 },
      {numero: 117, capacidad: 2, idAla: 1 },
      {numero: 118, capacidad: 2, idAla: 1 },
      {numero: 119, capacidad: 2, idAla: 1 },
      {numero: 120, capacidad: 2, idAla: 1 },
      {numero: 201, capacidad: 1 , idAla: 2},
      {numero: 202, capacidad: 1 , idAla: 2},
      {numero: 203, capacidad: 1 , idAla: 2},
      {numero: 204, capacidad: 1 , idAla: 2},
      {numero: 205, capacidad: 1 , idAla: 2},
      {numero: 206, capacidad: 1 , idAla: 2},
      {numero: 207, capacidad: 1 , idAla: 2},
      {numero: 208, capacidad: 1 , idAla: 2},
      {numero: 209, capacidad: 1 , idAla: 2},
      {numero: 210, capacidad: 1 , idAla: 2},
      {numero: 211, capacidad: 1 , idAla: 2},
      {numero: 212, capacidad: 1 , idAla: 2},
      {numero: 301, capacidad: 1 , idAla : 3},
      {numero: 302, capacidad: 1 , idAla : 3},
      {numero: 303, capacidad: 1 , idAla : 3},
      {numero: 304, capacidad: 1 , idAla : 3},
      {numero: 305, capacidad: 1 , idAla : 3},
      {numero: 306, capacidad: 1 , idAla : 3},
      {numero: 307, capacidad: 1 , idAla : 3},
      {numero: 308, capacidad: 1 , idAla : 3},
      {numero: 309, capacidad: 1 , idAla : 3},
      {numero: 310, capacidad: 1 , idAla : 3},
      {numero: 401, capacidad: 1 , idAla : 4},
      {numero: 402, capacidad: 1 , idAla : 4},
      {numero: 403, capacidad: 1 , idAla : 4},
      {numero: 404, capacidad: 1 , idAla : 4},
      {numero: 405, capacidad: 1 , idAla : 4},
      {numero: 406, capacidad: 1 , idAla : 4},
      {numero: 407, capacidad: 1 , idAla : 4},
      {numero: 408, capacidad: 1 , idAla : 4}
    ]);

    await Cama.bulkCreate([
      { numero: 1, estado: 'Libre', idHabitacion: 1 },
      { numero: 2, estado: 'Libre', idHabitacion: 1 },
      { numero: 1, estado: 'Mantenimiento', idHabitacion: 2 },
      { numero: 2, estado: 'Libre', idHabitacion: 2 },
      { numero: 1, estado: 'Libre', idHabitacion: 3 },
      { numero: 2, estado: 'Libre', idHabitacion: 3 },
      { numero: 1, estado: 'Libre', idHabitacion: 4 },
      { numero: 2, estado: 'Libre', idHabitacion: 4 },
      { numero: 1, estado: 'Mantenimiento', idHabitacion: 5 },
      { numero: 2, estado: 'Libre', idHabitacion: 5 },
      { numero: 1, estado: 'Libre', idHabitacion: 6 },
      { numero: 2, estado: 'Libre', idHabitacion: 6 },
      { numero: 1, estado: 'Libre', idHabitacion: 7 },
      { numero: 2, estado: 'Libre', idHabitacion: 7 },
      { numero: 1, estado: 'Libre', idHabitacion: 8 },
      { numero: 2, estado: 'Libre', idHabitacion: 8 },
      { numero: 1, estado: 'Libre', idHabitacion: 9 },
      { numero: 2, estado: 'Libre', idHabitacion: 9 },
      { numero: 1, estado: 'Libre', idHabitacion: 10 },
      { numero: 2, estado: 'Libre', idHabitacion: 10 },
      { numero: 1, estado: 'Libre', idHabitacion: 11 },
      { numero: 2, estado: 'Libre', idHabitacion: 11 },
      { numero: 1, estado: 'Mantenimiento', idHabitacion: 12 },
      { numero: 2, estado: 'Libre', idHabitacion: 12 },
      { numero: 1, estado: 'Libre', idHabitacion: 13 },
      { numero: 2, estado: 'Libre', idHabitacion: 13 },
      { numero: 1, estado: 'Libre', idHabitacion: 14 },
      { numero: 2, estado: 'Libre', idHabitacion: 14 },
      { numero: 1, estado: 'Libre', idHabitacion: 15 },
      { numero: 2, estado: 'Libre', idHabitacion: 15 },
      { numero: 1, estado: 'Libre', idHabitacion: 16 },
      { numero: 2, estado: 'Libre', idHabitacion: 16 },
      { numero: 1, estado: 'Libre', idHabitacion: 17 },
      { numero: 2, estado: 'Libre', idHabitacion: 17 },
      { numero: 1, estado: 'Mantenimiento', idHabitacion: 18 },
      { numero: 2, estado: 'Libre', idHabitacion: 18 },
      { numero: 1, estado: 'Libre', idHabitacion: 19 },
      { numero: 2, estado: 'Libre', idHabitacion: 19 },
      { numero: 1, estado: 'Libre', idHabitacion: 20 },
      { numero: 2, estado: 'Libre', idHabitacion: 20 },
      { numero: 1, estado: 'Libre', idHabitacion: 21 },
      { numero: 1, estado: 'Libre', idHabitacion: 22 },
      { numero: 1, estado: 'Libre', idHabitacion: 23 },
      { numero: 1, estado: 'Libre', idHabitacion: 24 },
      { numero: 1, estado: 'Libre', idHabitacion: 25 },
      { numero: 1, estado: 'Mantenimiento', idHabitacion: 26 },
      { numero: 1, estado: 'Libre', idHabitacion: 27 },
      { numero: 1, estado: 'Libre', idHabitacion: 28 },
      { numero: 1, estado: 'Libre', idHabitacion: 29 },
      { numero: 1, estado: 'Libre', idHabitacion: 30 },
      { numero: 1, estado: 'Libre', idHabitacion: 31 },
      { numero: 1, estado: 'Libre', idHabitacion: 32 },
      { numero: 1, estado: 'Mantenimiento', idHabitacion: 33 },
      { numero: 1, estado: 'Libre', idHabitacion: 34 },
      { numero: 1, estado: 'Libre', idHabitacion: 35 },
      { numero: 1, estado: 'Libre', idHabitacion: 36 },
      { numero: 1, estado: 'Libre', idHabitacion: 37 },
      { numero: 1, estado: 'Libre', idHabitacion: 38 },
      { numero: 1, estado: 'Libre', idHabitacion: 39 },
      { numero: 1, estado: 'Libre', idHabitacion: 40 },
      { numero: 1, estado: 'Libre', idHabitacion: 41 },
      { numero: 1, estado: 'Mantenimiento', idHabitacion: 42 },
      { numero: 1, estado: 'Libre', idHabitacion: 43 },
      { numero: 1, estado: 'Libre', idHabitacion: 44 },
      { numero: 1, estado: 'Libre', idHabitacion: 45 },
      { numero: 1, estado: 'Libre', idHabitacion: 46 },
      { numero: 1, estado: 'Libre', idHabitacion: 47 },
      { numero: 1, estado: 'Libre', idHabitacion: 48 },
      { numero: 1, estado: 'Mantenimiento', idHabitacion: 49 },
      { numero: 1, estado: 'Libre', idHabitacion: 50 }
    ]);

    await Paciente.bulkCreate([
      { dni: 30111222, nombre: 'Lucía', apellido: 'Pérez', genero: 'Femenino', fechaNacimiento: '1985-04-12', idNacionalidad: 1, domicilio: 'Calle Falsa 123', email: 'lucia.perez@mail.com', telefono: '1133445566' },
      { dni: 30111223, nombre: 'Juan', apellido: 'Gómez', genero: 'Masculino', fechaNacimiento: '1990-01-15', idNacionalidad: 12, domicilio: 'Av. Siempre Viva 742', email: 'juan.gomez@mail.com', telefono: '1122334455' },
      { dni: 30111224, nombre: 'María', apellido: 'López', genero: 'Femenino', fechaNacimiento: '1978-07-22', idNacionalidad: 45, domicilio: 'Calle 9 de Julio 100', email: 'maria.lopez@mail.com', telefono: '1144556677' },
      { dni: 30111225, nombre: 'Carlos', apellido: 'Fernández', genero: 'Masculino', fechaNacimiento: '1982-03-10', idNacionalidad: 33, domicilio: 'Calle Mitre 200', email: 'carlos.fernandez@mail.com', telefono: '1166778899' },
      { dni: 30111226, nombre: 'Ana', apellido: 'Martínez', genero: 'Femenino', fechaNacimiento: '1995-11-05', idNacionalidad: 78, domicilio: 'Calle Belgrano 321', email: 'ana.martinez@mail.com', telefono: '1177889900' },
      { dni: 30111227, nombre: 'Pedro', apellido: 'Sánchez', genero: 'Masculino', fechaNacimiento: '1988-09-18', idNacionalidad: 56, domicilio: 'Calle San Martín 456', email: 'pedro.sanchez@mail.com', telefono: '1188990011' },
      { dni: 30111228, nombre: 'Sofía', apellido: 'Díaz', genero: 'Femenino', fechaNacimiento: '1992-12-30', idNacionalidad: 102, domicilio: 'Calle Rivadavia 789', email: 'sofia.diaz@mail.com', telefono: '1199001122' },
      { dni: 30111229, nombre: 'Martín', apellido: 'Romero', genero: 'Masculino', fechaNacimiento: '1980-06-25', idNacionalidad: 67, domicilio: 'Calle Lavalle 654', email: 'martin.romero@mail.com', telefono: '1100112233' },
      { dni: 30111230, nombre: 'Valentina', apellido: 'Torres', genero: 'Femenino', fechaNacimiento: '1987-02-14', idNacionalidad: 89, domicilio: 'Calle Moreno 321', email: 'valentina.torres@mail.com', telefono: '1122443355' },
      { dni: 30111231, nombre: 'Diego', apellido: 'Ruiz', genero: 'Masculino', fechaNacimiento: '1993-08-19', idNacionalidad: 23, domicilio: 'Calle Sarmiento 987', email: 'diego.ruiz@mail.com', telefono: '1133554466' },
      { dni: 30111232, nombre: 'Camila', apellido: 'Silva', genero: 'Femenino', fechaNacimiento: '1984-05-03', idNacionalidad: 150, domicilio: 'Calle Pellegrini 111', email: 'camila.silva@mail.com', telefono: '1144665577' },
      { dni: 30111233, nombre: 'Lucas', apellido: 'Molina', genero: 'Masculino', fechaNacimiento: '1979-10-27', idNacionalidad: 17, domicilio: 'Calle Güemes 222', email: 'lucas.molina@mail.com', telefono: '1155776688' },
      { dni: 30111234, nombre: 'Florencia', apellido: 'Castro', genero: 'Femenino', fechaNacimiento: '1991-03-12', idNacionalidad: 99, domicilio: 'Calle Alberdi 333', email: 'florencia.castro@mail.com', telefono: '1166887799' },
      { dni: 30111235, nombre: 'Matías', apellido: 'Ortiz', genero: 'Masculino', fechaNacimiento: '1986-07-08', idNacionalidad: 44, domicilio: 'Calle Brown 444', email: 'matias.ortiz@mail.com', telefono: '1177998800' },
      { dni: 30111236, nombre: 'Julieta', apellido: 'Rojas', genero: 'Femenino', fechaNacimiento: '1994-01-21', idNacionalidad: 120, domicilio: 'Calle French 555', email: 'julieta.rojas@mail.com', telefono: '1188009911' },
      { dni: 30111237, nombre: 'Facundo', apellido: 'Acosta', genero: 'Masculino', fechaNacimiento: '1983-09-16', idNacionalidad: 61, domicilio: 'Calle Saavedra 666', email: 'facundo.acosta@mail.com', telefono: '1199110022' },
      { dni: 30111238, nombre: 'Agustina', apellido: 'Vega', genero: 'Femenino', fechaNacimiento: '1989-12-02', idNacionalidad: 80, domicilio: 'Calle Lamadrid 777', email: 'agustina.vega@mail.com', telefono: '1100221133' },
      { dni: 30111239, nombre: 'Nicolás', apellido: 'Cabrera', genero: 'Masculino', fechaNacimiento: '1996-04-28', idNacionalidad: 5, domicilio: 'Calle España 888', email: 'nicolas.cabrera@mail.com', telefono: '1111332244' },
      { dni: 30111240, nombre: 'Micaela', apellido: 'Ramos', genero: 'Femenino', fechaNacimiento: '1981-08-13', idNacionalidad: 132, domicilio: 'Calle Italia 999', email: 'micaela.ramos@mail.com', telefono: '1122443355' },
      { dni: 30111241, nombre: 'Javier', apellido: 'Medina', genero: 'Masculino', fechaNacimiento: '1985-11-29', idNacionalidad: 77, domicilio: 'Calle Chile 101', email: 'javier.medina@mail.com', telefono: '1133554466' },
      { dni: 30111242, nombre: 'Paula', apellido: 'Herrera', genero: 'Femenino', fechaNacimiento: '1990-02-17', idNacionalidad: 142, domicilio: 'Calle Brasil 202', email: 'paula.herrera@mail.com', telefono: '1144665577' },
      { dni: 30111243, nombre: 'Gonzalo', apellido: 'Aguilar', genero: 'Masculino', fechaNacimiento: '1987-06-23', idNacionalidad: 36, domicilio: 'Calle Perú 303', email: 'gonzalo.aguilar@mail.com', telefono: '1155776688' },
      { dni: 30111244, nombre: 'Milagros', apellido: 'Paredes', genero: 'Femenino', fechaNacimiento: '1992-10-09', idNacionalidad: 158, domicilio: 'Calle Bolivia 404', email: 'milagros.paredes@mail.com', telefono: '1166887799' },
      { dni: 30111245, nombre: 'Tomás', apellido: 'Méndez', genero: 'Masculino', fechaNacimiento: '1984-12-31', idNacionalidad: 13, domicilio: 'Calle Uruguay 505', email: 'tomas.mendez@mail.com', telefono: '1177998800' },
      { dni: 30111246, nombre: 'Rocío', apellido: 'Morales', genero: 'Femenino', fechaNacimiento: '1977-05-06', idNacionalidad: 170, domicilio: 'Calle Paraguay 606', email: 'rocio.morales@mail.com', telefono: '1188009911' },
      { dni: 30111247, nombre: 'Federico', apellido: 'Flores', genero: 'Masculino', fechaNacimiento: '1991-09-15', idNacionalidad: 29, domicilio: 'Calle Venezuela 707', email: 'federico.flores@mail.com', telefono: '1199110022' },
      { dni: 30111248, nombre: 'Gabriela', apellido: 'Benítez', genero: 'Femenino', fechaNacimiento: '1986-03-19', idNacionalidad: 54, domicilio: 'Calle Ecuador 808', email: 'gabriela.benitez@mail.com', telefono: '1100221133' },
      { dni: 30111249, nombre: 'Santiago', apellido: 'Luna', genero: 'Masculino', fechaNacimiento: '1993-07-27', idNacionalidad: 101, domicilio: 'Calle Francia 909', email: 'santiago.luna@mail.com', telefono: '1111332244' },
      { dni: 30111250, nombre: 'Martina', apellido: 'Campos', genero: 'Femenino', fechaNacimiento: '1982-11-11', idNacionalidad: 63, domicilio: 'Calle Alemania 123', email: 'martina.campos@mail.com', telefono: '1122443355' },
      { dni: 30111251, nombre: 'Emiliano', apellido: 'Vargas', genero: 'Masculino', fechaNacimiento: '1988-01-03', idNacionalidad: 88, domicilio: 'Calle Suiza 234', email: 'emiliano.vargas@mail.com', telefono: '1133554466' },
      { dni: 30111252, nombre: 'Josefina', apellido: 'Mora', genero: 'Femenino', fechaNacimiento: '1995-06-20', idNacionalidad: 110, domicilio: 'Calle Austria 345', email: 'josefina.mora@mail.com', telefono: '1144665577' },
      { dni: 30111253, nombre: 'Leandro', apellido: 'Navarro', genero: 'Masculino', fechaNacimiento: '1981-04-17', idNacionalidad: 25, domicilio: 'Calle Bélgica 456', email: 'leandro.navarro@mail.com', telefono: '1155776688' },
      { dni: 30111254, nombre: 'Malena', apellido: 'Sosa', genero: 'Femenino', fechaNacimiento: '1989-08-25', idNacionalidad: 134, domicilio: 'Calle Noruega 567', email: 'malena.sosa@mail.com', telefono: '1166887799' },
      { dni: 30111255, nombre: 'Bruno', apellido: 'Ibarra', genero: 'Masculino', fechaNacimiento: '1978-12-14', idNacionalidad: 73, domicilio: 'Calle Suecia 678', email: 'bruno.ibarra@mail.com', telefono: '1177998800' },
      { dni: 30111256, nombre: 'Ailén', apellido: 'Ferreyra', genero: 'Femenino', fechaNacimiento: '1992-02-08', idNacionalidad: 159, domicilio: 'Calle Dinamarca 789', email: 'ailen.ferreyra@mail.com', telefono: '1188009911' },
      { dni: 30111257, nombre: 'Ramiro', apellido: 'Ponce', genero: 'Masculino', fechaNacimiento: '1985-05-30', idNacionalidad: 41, domicilio: 'Calle Finlandia 890', email: 'ramiro.ponce@mail.com', telefono: '1199110022' },
      { dni: 30111258, nombre: 'Celeste', apellido: 'Villar', genero: 'Femenino', fechaNacimiento: '1990-10-02', idNacionalidad: 146, domicilio: 'Calle Hungría 901', email: 'celeste.villar@mail.com', telefono: '1100221133' },
      { dni: 30111259, nombre: 'Franco', apellido: 'Bravo', genero: 'Masculino', fechaNacimiento: '1983-07-19', idNacionalidad: 60, domicilio: 'Calle Polonia 234', email: 'franco.bravo@mail.com', telefono: '1111332244' },
      { dni: 30111260, nombre: 'Bárbara', apellido: 'Maldonado', genero: 'Femenino', fechaNacimiento: '1987-11-23', idNacionalidad: 121, domicilio: 'Calle Grecia 345', email: 'barbara.maldonado@mail.com', telefono: '1122443355' },
      { dni: 30111261, nombre: 'Rodrigo', apellido: 'Rivas', genero: 'Masculino', fechaNacimiento: '1994-03-07', idNacionalidad: 8, domicilio: 'Calle Turquía 456', email: 'rodrigo.rivas@mail.com', telefono: '1133554466' },
      { dni: 30111262, nombre: 'Marina', apellido: 'Salas', genero: 'Femenino', fechaNacimiento: '1980-09-28', idNacionalidad: 175, domicilio: 'Calle Irlanda 567', email: 'marina.salas@mail.com', telefono: '1144665577' },
      { dni: 30111263, nombre: 'Esteban', apellido: 'Correa', genero: 'Masculino', fechaNacimiento: '1986-06-16', idNacionalidad: 52, domicilio: 'Calle Portugal 678', email: 'esteban.correa@mail.com', telefono: '1155776688' },
      { dni: 30111264, nombre: 'Noelia', apellido: 'Peña', genero: 'Femenino', fechaNacimiento: '1991-12-04', idNacionalidad: 138, domicilio: 'Calle Rusia 789', email: 'noelia.pena@mail.com', telefono: '1166887799' },
      { dni: 30111265, nombre: 'Alejandro', apellido: 'Godoy', genero: 'Masculino', fechaNacimiento: '1984-08-11', idNacionalidad: 19, domicilio: 'Calle Ucrania 890', email: 'alejandro.godoy@mail.com', telefono: '1177998800' },
      { dni: 30111266, nombre: 'Lorena', apellido: 'Palacios', genero: 'Femenino', fechaNacimiento: '1988-05-27', idNacionalidad: 164, domicilio: 'Calle Croacia 901', email: 'lorena.palacios@mail.com', telefono: '1188009911' },
      { dni: 30111267, nombre: 'Maximiliano', apellido: 'Vera', genero: 'Masculino', fechaNacimiento: '1993-01-13', idNacionalidad: 31, domicilio: 'Calle Serbia 123', email: 'maximiliano.vera@mail.com', telefono: '1199110022' },
      { dni: 30111268, nombre: 'Victoria', apellido: 'Montoya', genero: 'Femenino', fechaNacimiento: '1979-04-29', idNacionalidad: 140, domicilio: 'Calle Eslovaquia 234', email: 'victoria.montoya@mail.com', telefono: '1100221133' },
      { dni: 30111269, nombre: 'Pablo', apellido: 'Peralta', genero: 'Masculino', fechaNacimiento: '1982-10-18', idNacionalidad: 70, domicilio: 'Calle Eslovenia 345', email: 'pablo.peralta@mail.com', telefono: '1111332244' },
      { dni: 30111270, nombre: 'Daniela', apellido: 'Roldán', genero: 'Femenino', fechaNacimiento: '1996-07-22', idNacionalidad: 104, domicilio: 'Calle Estonia 456', email: 'daniela.roldan@mail.com', telefono: '1122443355' },
      { dni: 30111271, nombre: 'Florencia', apellido: 'Pena', genero: 'Femenino', fechaNacimiento: '1996-07-22', idNacionalidad: 104, domicilio: 'Calle Estonia 459', email: 'daniela.roldan@mail.com', telefono: '1122443356' },
      { dni: 30111272, nombre: 'Camila', apellido: 'Baez', genero: 'Femenino', fechaNacimiento: '1996-07-22', idNacionalidad: 104, domicilio: 'Calle Estonia 463', email: 'daniela.roldan@mail.com', telefono: '1122443357' }
    ]);

    await SeguroMedico.bulkCreate([
      { nombre: 'OSDE' },
      { nombre: 'Swiss Medical' },
      { nombre: 'Galeno' },
      { nombre: 'Medifé' },
      { nombre: 'Omint' },
      { nombre: 'Sancor Salud' },
      { nombre: 'Hospital Italiano' },
      { nombre: 'PAMI' }
    ]);
    const today = new Date();
    const pad = n => n.toString().padStart(2, '0');
    const formatDate = d => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;

    const turnos = [];
    // 9 turnos con la fecha de hoy
    for (let i = 1; i <= 9; i++) {
      turnos.push({
      fechaTurno: formatDate(today),
      idPaciente: i,
      estado: true
      });
    }
    // 41 turnos con fecha superior a la de hoy
    for (let i = 10; i <= 50; i++) {
      const futureDate = new Date(today);
      futureDate.setDate(today.getDate() + (i - 9));
      turnos.push({
      fechaTurno: formatDate(futureDate),
      idPaciente: i,
      estado: true
      });
    }
    await Turno.bulkCreate(turnos);
    console.log('Datos insertados correctamente');
    process.exit(0);
  } catch (error) {
    console.error('Error al cargar datos:', error);
    process.exit(1);
  }
})();
